language: node_js
node_js:
  - latest
 
before_script:
  - npm install -g @angular/cli

script:
  - npm install
  - npm run build

deploy:
  skip_cleanup: true
  provider: firebase
  only:
    - master
  token:
    FIREBASE_TOKEN